<#ftl output_format="XML">
        <entry>
         <int>${macroIndex}</int>
         <net.rptools.maptool.model.MacroButtonProperties>
           <saveLocation></saveLocation>
           <index>${macroIndex}</index>
           <colorKey>${macroDef.buttonBackgroundColor}</colorKey>
           <hotKey>${macroDef.hotKey}</hotKey>
           <command>
${macroDef.definition}
           </command>
           <label>${macroDef.buttonLabel}</label>
           <group>${macroDef.buttonGoup}</group>
           <sortby>${macroDef.sortBy}</sortby>
           <autoExecute>${macroDef.autoExecute?c}</autoExecute>
           <includeLabel>${macroDef.includeLabel?c}</includeLabel>
           <applyToTokens>${macroDef.applyToTokens?c}</applyToTokens>
           <fontColorKey>${macroDef.buttonTextColor}</fontColorKey>
           <fontSize>1.00em</fontSize>
           <minWidth>${macroDef.width}</minWidth>
           <maxWidth>${macroDef.width}</maxWidth>
           <allowPlayerEdits>${macroDef.allowPlayerEdits?c}</allowPlayerEdits>
           <toolTip>${(macroDef.toolTip)!}</toolTip>
           <commonMacro>false</commonMacro>
           <compareGroup>true</compareGroup>
           <compareIncludeLabel>true</compareIncludeLabel>
           <compareAutoExecute>true</compareAutoExecute>
           <compareApplyToSelectedTokens>true</compareApplyToSelectedTokens>
         </net.rptools.maptool.model.MacroButtonProperties>
       </entry>
