 <net.rptools.maptool.model.Token>
   <id>
     <baGUID>fwABASo0c8kCAAAASQAAAA==</baGUID>
    </id>
    <beingImpersonated>false</beingImpersonated>
    <imageAssetMap>
      <entry>
        <null/>
        <net.rptools.lib.MD5Key>
          <id>${character.tokenMD5}</id>
        </net.rptools.lib.MD5Key>
      </entry>
      <entry>
        <string>${character.name}</string>
        <net.rptools.lib.MD5Key reference="../../entry/net.rptools.lib.MD5Key"/>
      </entry>
    </imageAssetMap>
    <currentImageAsset>${character.name}</currentImageAsset>
      <x>0</x>
      <y>0</y>
      <z>0</z>
      <anchorX>0</anchorX>
      <anchorY>0</anchorY>
      <sizeScale>1.0</sizeScale>
      <lastX>0</lastX>
      <lastY>0</lastY>
      <snapToScale>true</snapToScale>
      <width>0</width>
      <height>0</height>
      <scaleX>1.0</scaleX>
      <scaleY>1.0</scaleY>
      <sizeMap>
        <entry>
          <java-class>net.rptools.maptool.model.SquareGrid</java-class>
          <net.rptools.maptool.model.GUID>
            <baGUID>${character.tokenSize}</baGUID>
          </net.rptools.maptool.model.GUID>
        </entry>
      </sizeMap>
      <snapToGrid>true</snapToGrid>
      <isVisible>true</isVisible>
      <visibleOnlyToOwner>false</visibleOnlyToOwner>
      <name>${character.name}</name>
      <ownerType>0</ownerType>
      <tokenShape>CIRCLE</tokenShape>
      <tokenType>${character.role?upper_case}</tokenType>
      <propertyType>Basic</propertyType>
      <isFlippedX>false</isFlippedX>
      <isFlippedY>false</isFlippedY>
      <charsheetImage>
        <id>${character.portraitMD5}</id>
      </charsheetImage>
      <portraitImage reference="../charsheetImage"/>
      <sightType>${character.vision}</sightType>
      <hasSight>true</hasSight>
      <state/>
      <propertyMapCI>
        <store>
${properties}
        </store>
      </propertyMapCI>
    <macroPropertiesMap>
${macros}
    </macroPropertiesMap>
    <speechMap/>
  </net.rptools.maptool.model.Token>
